In [39]:
import torch
from opt_nets import MyNetwork
import numpy as np
from submission_utils import general_weights_fixer, get_submission_markowitz, test_submission
import pandas as pd
from data_utils import read_all_candles, get_total_df_from_candles

In [47]:
model = MyNetwork(96)

In [48]:
model.load_state_dict(torch.load("models_2103/mynet_data1.pt"))

<All keys matched successfully>

In [56]:
w_pred = (
        model
        .to("cpu")(torch.ones(1, 4, 24, 96).cpu())
        .cpu()
        .detach()
        .numpy()
        .squeeze()
    )

In [50]:
w_pred

array([-0.04269977, -0.01086361,  0.02353076, -0.0003572 ,  0.07330152,
        0.09324348,  0.01085217,  0.01331394,  0.02735762,  0.02482372,
        0.05871332,  0.0687267 , -0.02000595,  0.02037644, -0.03051005,
       -0.01579612,  0.01834748, -0.05626231,  0.02641034,  0.02785983,
        0.05049424,  0.02355445,  0.00920694,  0.01615367,  0.00252266,
        0.04405974, -0.03837409,  0.06593949,  0.03295088, -0.00383286,
       -0.01184154,  0.00268191,  0.00188101, -0.00756512,  0.05213875,
        0.01019803,  0.0403369 ,  0.02707646,  0.03596102,  0.01033906,
        0.05448176,  0.05551405, -0.19032608, -0.01887788,  0.10829149,
        0.02900984,  0.03525766,  0.03846399,  0.02650115,  0.0116521 ,
        0.00229101,  0.00321894,  0.03312023,  0.02611092,  0.02232998,
        0.00848812, -0.00503923, -0.01036897,  0.01602357,  0.00606979,
        0.0354757 ,  0.01162198,  0.01527124, -0.01249822, -0.00316703,
        0.0105366 ,  0.06309432, -0.01075389, -0.00520499, -0.02

In [5]:
w_pred

array([ 0.03597331,  0.04094472, -0.04062497, -0.03214501,  0.13300109,
        0.01582367, -0.01072782, -0.00667011, -0.03485004, -0.04461594,
        0.0072149 ,  0.08948692,  0.01068651,  0.0945    ,  0.06416709,
        0.11793721, -0.05036531,  0.11605453, -0.04607381,  0.12886472,
       -0.07517177,  0.1094099 , -0.14892806,  0.11546078, -0.04276541,
        0.0440218 ,  0.08822036,  0.05736258, -0.03219866, -0.1089143 ,
       -0.02099176,  0.02136542, -0.01528573,  0.0376837 ,  0.10916466,
        0.02686227, -0.01793947,  0.06293159, -0.00239908,  0.04774387,
        0.10318008,  0.02270579, -0.08384003,  0.0467216 , -0.08453764,
       -0.1126596 ,  0.04095422,  0.16299564,  0.02324608, -0.09840321,
       -0.06062863, -0.00098917,  0.02074906,  0.10867736,  0.00591856,
       -0.03702607,  0.03917286,  0.03631908,  0.09568173,  0.02622367,
       -0.18297563, -0.09952974,  0.07529292,  0.13721141, -0.05122282,
        0.04109402, -0.0083485 , -0.02724842,  0.0178959 , -0.01

In [51]:
w_pred = np.array([ 0.03597331,  0.04094472, -0.04062497, -0.03214501,  0.13300109,
        0.01582367, -0.01072782, -0.00667011, -0.03485004, -0.04461594,
        0.0072149 ,  0.08948692,  0.01068651,  0.0945    ,  0.06416709,
        0.11793721, -0.05036531,  0.11605453, -0.04607381,  0.12886472,
       -0.07517177,  0.1094099 , -0.14892806,  0.11546078, -0.04276541,
        0.0440218 ,  0.08822036,  0.05736258, -0.03219866, -0.1089143 ,
       -0.02099176,  0.02136542, -0.01528573,  0.0376837 ,  0.10916466,
        0.02686227, -0.01793947,  0.06293159, -0.00239908,  0.04774387,
        0.10318008,  0.02270579, -0.08384003,  0.0467216 , -0.08453764,
       -0.1126596 ,  0.04095422,  0.16299564,  0.02324608, -0.09840321,
       -0.06062863, -0.00098917,  0.02074906,  0.10867736,  0.00591856,
       -0.03702607,  0.03917286,  0.03631908,  0.09568173,  0.02622367,
       -0.18297563, -0.09952974,  0.07529292,  0.13721141, -0.05122282,
        0.04109402, -0.0083485 , -0.02724842,  0.0178959 , -0.01292974,
        0.04584829, -0.10800822, -0.00070954,  0.08412293, -0.12645903,
       -0.06100564,  0.03880786,  0.07400165,  0.11399937,  0.02537919,
       -0.03763306,  0.08655306, -0.04641252, -0.12354543, -0.09337219,
        0.02458405,  0.02474253,  0.06085989, -0.03006249,  0.02554653,
       -0.05082734, -0.13278869,  0.03757695,  0.10195067,  0.1099275 ,
       -0.0309913 ])

In [11]:
weights = np.clip(w_pred, 0, 1)

In [12]:
weights.sum()

3.432822

In [13]:
weights = weights / weights.sum()

In [15]:
weights.sum()

1.0

In [16]:
weights

array([0.01047922, 0.01192742, 0.        , 0.        , 0.03874395,
       0.00460952, 0.        , 0.        , 0.        , 0.        ,
       0.00210174, 0.02606803, 0.00311304, 0.02752837, 0.01869223,
       0.03435576, 0.        , 0.03380733, 0.        , 0.03753901,
       0.        , 0.03187171, 0.        , 0.03363436, 0.        ,
       0.01282379, 0.02569908, 0.01671004, 0.        , 0.        ,
       0.        , 0.00622386, 0.        , 0.01097747, 0.03180027,
       0.00782513, 0.        , 0.01833232, 0.        , 0.01390805,
       0.03005693, 0.00661432, 0.        , 0.01361026, 0.        ,
       0.        , 0.01193019, 0.04748153, 0.00677171, 0.        ,
       0.        , 0.        , 0.00604431, 0.03165832, 0.00172411,
       0.        , 0.01141127, 0.01057995, 0.02787262, 0.0076391 ,
       0.        , 0.        , 0.02193324, 0.03997044, 0.        ,
       0.01197091, 0.        , 0.        , 0.00521317, 0.        ,
       0.01335586, 0.        , 0.        , 0.02450548, 0.     

In [18]:
submission_1602 = pd.read_csv("submission_1602_2.csv")

In [23]:
#submission_1602.iloc[0, :].values[1:].dtype

In [25]:
candles = read_all_candles()

Getting candles data for Darwins...: 100%|██████████| 96/96 [00:01<00:00, 49.94it/s]


In [26]:
asset_names = [k for k in candles.keys()]

In [57]:
assets_0_2 = [
    asset for asset, weight in zip(asset_names, w_pred)
    if weight <= 0
]

In [58]:
assets_0_2

['ZVQ',
 'NCT',
 'OOS',
 'CSB',
 'UYZ',
 'TRO',
 'ERO',
 'AWW',
 'ACY',
 'MMY',
 'LUG',
 'LWK',
 'ZCD',
 'LHB',
 'NYD',
 'BFS',
 'SKN',
 'GGR',
 'TER',
 'NYP',
 'EOP',
 'PME',
 'FNM',
 'EEY',
 'ERQ',
 'AZG',
 'OJG',
 'WWT',
 'BOT',
 'TXR',
 'DIG',
 'PHI']

In [35]:
w_dict = {
    asset: w / sum(general_weights_fixer(weights))
    for asset, w in zip(asset_names, general_weights_fixer(weights))
}

In [36]:
sum(w_dict.values())

1.0

In [37]:
w_dict.values()

dict_values([0.009999999776482582, 0.012000000104308128, 0.0, 0.0, 0.039000000804662704, 0.004999999888241291, 0.0, 0.0, 0.0, 0.0, 0.0020000000949949026, 0.026000000536441803, 0.003000000026077032, 0.02800000086426735, 0.01899999938905239, 0.03400000184774399, 0.0, 0.03400000184774399, 0.0, 0.03799999877810478, 0.0, 0.03200000151991844, 0.0, 0.03400000184774399, 0.0, 0.013000000268220901, 0.026000000536441803, 0.017000000923871994, 0.0, 0.0, 0.0, 0.006000000052154064, 0.0, 0.010999999940395355, 0.03200000151991844, 0.00800000037997961, 0.0, 0.017999999225139618, 0.0, 0.014000000432133675, 0.029999999329447746, 0.007000000216066837, 0.0, 0.014000000432133675, 0.0, 0.0, 0.012000000104308128, 0.0439999857917428, 0.007000000216066837, 0.0, 0.0, 0.0, 0.006000000052154064, 0.03200000151991844, 0.0020000000949949026, 0.0, 0.010999999940395355, 0.010999999940395355, 0.02800000086426735, 0.00800000037997961, 0.0, 0.0, 0.02199999988079071, 0.03999999910593033, 0.0, 0.012000000104308128, 0.0, 0.0

In [40]:
submission = get_submission_markowitz(w_dict, asset_names)

In [41]:
test_submission(submission)

In [42]:
submission.head()

allo_ZVQ  allo_NCT  allo_YAX  allo_OOS  allo_GFJ  \
eod_ts                                                                  
2020-08-18 00:00:00      0.01     0.012       0.0       0.0     0.039   
2020-08-18 01:00:00      0.01     0.012       0.0       0.0     0.039   
2020-08-18 02:00:00      0.01     0.012       0.0       0.0     0.039   
2020-08-18 03:00:00      0.01     0.012       0.0       0.0     0.039   
2020-08-18 04:00:00      0.01     0.012       0.0       0.0     0.039   

                     allo_FIR  allo_USX  allo_FSK  allo_TMF  allo_TDD  ...  \
eod_ts                                                                 ...   
2020-08-18 00:00:00     0.005       0.0       0.0       0.0       0.0  ...   
2020-08-18 01:00:00     0.005       0.0       0.0       0.0       0.0  ...   
2020-08-18 02:00:00     0.005       0.0       0.0       0.0       0.0  ...   
2020-08-18 03:00:00     0.005       0.0       0.0       0.0       0.0  ...   
2020-08-18 04:00:00     0.005       0.0       0.0       0.0       0.0  ...   

                     allo_AZG  allo_OJG  allo_WWT  allo_BOT  allo_TXR  \
eod_ts                                                                  
2020-08-18 00:00:00     0.007     0.018       0.0     0.007       0.0   
2020-08-18 01:00:00     0.007     0.018       0.0     0.007       0.0   
2020-08-18 02:00:00     0.007     0.018       0.0     0.007       0.0   
2020-08-18 03:00:00     0.007     0.018       0.0     0.007       0.0   
2020-08-18 04:00:00     0.007     0.018       0.0     0.007       0.0   

                     allo_RAT  allo_DIG  allo_SRI  allo_PHI  allo_RWJ  
eod_ts                                                                 
2020-08-18 00:00:00       0.0     0.011      0.03     0.032       0.0  
2020-08-18 01:00:00       0.0     0.011      0.03     0.032       0.0  
2020-08-18 02:00:00       0.0     0.011      0.03     0.032       0.0  
2020-08-18 03:00:00       0.0     0.011      0.03     0.032       0.0  
2020-08-18 04:00:00       0.0     0.011      0.03     0.032       0.0  

[5 rows x 96 columns]

In [43]:
all(submission.sum(axis=1) == 1)

True

In [44]:
all(submission >= 0)

True

In [46]:
submission.to_csv("submission_2203.csv", header=True, index=True)